### ISSUE TITLE
Chall12 accidental code blocks

### ISSUE THREAD

**Issue by eah13** [silshack/summer2017#324]
@chall12 check your app reflection and your peer review.  The spaces before your paragraphs (i.e. indentation) are interpreted as code blocks (that's an alternate way to write code beyond using backticks).  Removing the extra spaces before each paragraph will fix this.

**Comment by chall12** [comment]
@eah13 Thanks for pointing that out! Edits are in pull requests #339 and #340

**Comment by eah13** [comment]
Fixed by #339 and #340
