### ISSUE TITLE
@jbfelder - review of your first 3 posts

### ISSUE THREAD

**Issue by chall12** [silshack/summer2017#54]
First Post: His first post has all of the components and looks good. His post made me hungry for pizza!
First Post Edit: His edits to his first post also look good.
Turtle Hack Post: He had a different trinket link, but is going to edit it! After that, it'll look perfect.

**Comment by eah13** [comment]
@chall12 @jbfelder What's the status of this issue?  Did the turtle hack edits occur?  If so, on what pull request number?  Let's reference that with a `#`.

**Comment by chall12** [comment]
@eah13 @jbfelder  Not yet!  Pull Request #36
