### ISSUE TITLE
Issue - Ibbi2010's turtle hack

### ISSUE THREAD

**Issue by WildGinger23** [silshack/summer2017#56]
I noticed a minor issue while reading through the reflection on your pull request.

You said the following, "using (“to,go”) code to...", reference the go.to command,

We learned today in class to use back ticks, below the tilde, to talk about code in Github, while I'm still uncertain whether its necessary to use them for commands it could be useful.

**Comment by Ibbi2010** [comment]
Thank you! fixed it.
